# i was bored of writing a proper compiler so
# here is a "temporary" one until i write
# a real one.
#
# edit: i'll probably end up keeping this
# so get used to this un-modular,
# poorley commented, ugly lump of code.
# plus it's full of crypticly named vars.
# enjoy.

import sys

f_in = sys.argv[1]
f_out = sys.argv[0]

with open(f_in,"r") as r_file:
    m_src = r_file.read()

# last line indent level
lind_lvl = 0
# are we currently in a string
in_str = False
# string start pos
str_start = 0
# these are both the position in the file
# FIXME: line number is calculated incorrectly:
# if you skip over \n ex: while examining an
# if statement
#
# solution: add a get_line function
cursor = 0
ln_num = 0

simple_st = ["if","elif","while"]

# this block contains reserved words
mutt_mcr = """/* auto generated by mutt */
#define elif else if
#define not !
#define and &&
#define or ||
#define true 1
#define false 0
#define bool _Bool
/* src begins here */

"""

def is_notspace(string):
    return (string.isalpha() or string.isdigit()) and not string.isspace() # isspace might be redundant

def get_next_wrd(src,cursor):
    cursor_p = cursor
    word = ""
    src_sz = len(src)
    word_s = cursor
    word_f = cursor
    while(cursor_p<src_sz and not is_notspace(src[cursor_p])):
        cursor_p +=1
    word_s = cursor_p
    while(cursor_p<src_sz and is_notspace(src[cursor_p])):
        word += src[cursor_p]
        cursor_p +=1
    word_f = cursor_p
    return (word_s,word_f,word)

def insert_at(string, thing, place):
    return string[:place] + thing + string[place:]

def set_at(string, thing, place):
    new_str = list(string) 
    new_str[place] = thing
    return "".join(new_str)

def chop_at(string, start, end):
    return string[:start] + string[start+abs(end-start):]

def get_stmnt(src,cursor):
    p_cursor = cursor
    in_str = False
    no_colon = True
    while(p_cursor<len(src)): 
        chara = src[p_cursor] 
        if chara == "\"" and not m_src[cursor-1] == "\\":
            in_str = not in_str
            str_start = p_cursor
        elif chara == ":" and not in_str:
            no_colon = False
            break
        p_cursor+=1
    if no_colon or in_str:
        #TODO: add error and stop compiler
        print("if statement unfinished")
    return p_cursor

def block_line(src,cursor):
    p_cursor = cursor
    while(p_cursor<len(src)): 
        char = src[p_cursor]
        if(char == "\n"):
            return True
        elif(is_notspace(char)):
            return False
        p_cursor += 1
    # TODO: handle error
    print("expected line after statement or function")
    return False

# begin compilation
while(cursor<len(m_src)):
    # this is string thing
    chara=m_src[cursor]
    if chara == "\"" and not m_src[cursor-1] == "\\":
        in_str = not in_str
        str_start = ln_num
    elif chara == "\n":
        ln_num += 1
    elif chara == "\t" and m_src[cursor-1] == "\n":
        # TODO: handle indentation and semicolons
        pass
    elif not in_str:
        start,finish,word = get_next_wrd(m_src,cursor)
        if word in simple_st:
            cursor = finish
            m_src = insert_at(m_src,"(",cursor)
            # TODO: handle possible errors
            close_if = get_stmnt(m_src,cursor)
            m_src = set_at(m_src,")",close_if)
            m_src = insert_at(m_src,"{",close_if+1)
            cursor = close_if+1
        elif word == "else":
            cursor = finish
            # TODO: handle possible errors
            close_if = get_stmnt(m_src,cursor)
            m_src = chop_at(m_src,close_if,close_if+1)
            # since we cut a letter out the cursor is now ahead by one 
            m_src = insert_at(m_src,"{",close_if)
        elif word == "func":
            # TODO: clean some of this up and offload it to another functions
            cursor = start
            m_src = chop_at(m_src,start,finish)
            name_start,name_end,name = get_next_wrd(m_src,cursor)
            # TODO: make this section get_p_contents
            p_cursor = cursor
            no_opening = True
            no_closing = True
            inner_str = ""
            p_start = cursor
            p_end = cursor
            while(p_cursor<len(m_src)):
                  if(m_src[p_cursor] == "("):
                      no_opening = False
                      p_start = p_cursor
                      p_cursor += 1
                      break
                  p_cursor += 1
            if no_opening:
                  #TODO: handle this error properly
                  print("their's something wrong with your func")
                  #return
            while(p_cursor<len(m_src)):
                  if(m_src[p_cursor] == ")"):
                      no_closing = False
                      p_end = p_cursor
                      p_cursor += 1
                      break
                  inner_str += m_src[p_cursor]
                  p_cursor += 1
            if no_closing:
                  #TODO: also handle this error properly
                  print("their's something else wrong with your func")
                  #return
            # end of bad section
            # TODO: make this section get_c_args
            m_args = inner_str.split(",")
            c_args = []
            for arg in m_args:
                  if len(arg) == 0:
                        # their is no args, so we'll just break the for loop.
                        break
                  if "[" in arg:
                        # TODO: do something with this error (again)
                        print("arrays cannot be arguments (try a pointer)")
                        #return
                  arg = arg.split(":")
                  if not len(arg) == 2:
                        # TODO: handle this
                        print("invalid number of types")
                        #return
                  c_args.append(f"{arg[1]} {arg[0]}")
            c_args = str(c_args).replace("[","").replace("]","").replace("'","")
            # end of bad section
            rtrn_s,rtrn_e,return_type = get_next_wrd(m_src,p_end)
            # TODO: move it - get_func_end
            p_cursor = rtrn_s
            no_ending = True
            while(p_cursor<len(m_src)):
                  if(m_src[p_cursor] == ":"):
                      no_ending = False
                      p_cursor += 1
                      break
                  p_cursor += 1
            if no_ending:
                # TODO: you know the drill
                print("function never ended are you missing an \":\"")
                #return
            # end of awful code
            f_end = p_cursor
            o_sz = len(m_src)
            m_src = chop_at(m_src,p_end+1,f_end)
            m_src = insert_at(m_src,"{",p_end+1)
            m_src = chop_at(m_src,p_start,p_end+1)
            m_src = insert_at(m_src,f"({c_args})",p_start)
            m_src = insert_at(m_src,return_type,cursor)
            delta_sz = len(m_src)-o_sz
            cursor = f_end+delta_sz
            if(not block_line(m_src,cursor)):
                print("please do not place code on the same line as the function")
                print("sic em' mutt!")
                # refuse to compile the code
                sys.exit(-1)
                
    cursor += 1
m_src = mutt_mcr+m_src

if in_str:
    print(f"unclosed string starting on line: {ln_num}")
print(m_src)
